version: 2
jobs:
    build:
        working_directory: ~/mern-starter
        docker:
            - image: circleci/node:8-stretch
        steps:
            - checkout
            - run:
                name: Update npm
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
    lint:
        docker:
            - image: circleci/node:8-stretch
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Installing Dependencies
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Running Lint Checks
                command: npm run lint
    integration-tests:
        docker:
            - image: circleci/node:8-stretch
            - image: circleci/redis
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Installing Dependencies
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Running Mocha Tests
                command: NODE_ENV=test npm run test:integration
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - lint:
                requires:
                    - build
            - integration-tests:
                requires:
                    - build
